# Code

In [1]:
import os

In [2]:
os.chdir('..')

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('data/raw/employment.csv')

In [5]:
df.rename(columns={'Unnamed: 0': 'id'}, inplace=True)
df.columns

Index(['id', 'Age', 'Accessibility', 'EdLevel', 'Employment', 'Gender',
       'MentalHealth', 'MainBranch', 'YearsCode', 'YearsCodePro', 'Country',
       'PreviousSalary', 'HaveWorkedWith', 'ComputerSkills', 'Employed'],
      dtype='str')

In [6]:
df[df['HaveWorkedWith'].isna()]

,id,Age,Accessibility,EdLevel,Employment,Gender,MentalHealth,MainBranch,YearsCode,YearsCodePro,Country,PreviousSalary,HaveWorkedWith,ComputerSkills,Employed
1161,1161,>35,No,Undergraduate,1,Man,Yes,Dev,36,32,Switzerland,96566.0,NaN,0,0
2443,2443,>35,No,Other,1,Man,No,Dev,7,6,United States of America,85000.0,NaN,0,0
2533,2533,>35,No,PhD,1,Man,No,NotDev,37,0,Germany,76020.0,NaN,0,0
2657,2657,<35,No,Master,0,Woman,No,Dev,11,5,Portugal,31428.0,NaN,0,0
5797,5797,<35,No,Undergraduate,1,Man,No,Dev,8,4,India,70368.0,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69865,69865,<35,No,Other,1,Man,No,Dev,0,0,Colombia,6036.0,NaN,0,0
71795,71795,<35,No,Undergraduate,1,Man,No,Dev,7,3,Bangladesh,5460.0,NaN,0,0
72153,72153,>35,Yes,Other,1,Man,No,NotDev,12,2,Germany,106644.0,NaN,0,0
72588,72588,<35,No,Other,1,Man,Yes,Dev,10,6,Spain,41058.0,NaN,0,0
72593,72593,<35,No,Undergraduate,1,Woman,No,Dev,8,5,Ukraine,63600.0,NaN,0,0

In [7]:
df[(df['ComputerSkills'] == 0) | df['HaveWorkedWith'].isna()]

,id,Age,Accessibility,EdLevel,Employment,Gender,MentalHealth,MainBranch,YearsCode,YearsCodePro,Country,PreviousSalary,HaveWorkedWith,ComputerSkills,Employed
1161,1161,>35,No,Undergraduate,1,Man,Yes,Dev,36,32,Switzerland,96566.0,NaN,0,0
2443,2443,>35,No,Other,1,Man,No,Dev,7,6,United States of America,85000.0,NaN,0,0
2533,2533,>35,No,PhD,1,Man,No,NotDev,37,0,Germany,76020.0,NaN,0,0
2657,2657,<35,No,Master,0,Woman,No,Dev,11,5,Portugal,31428.0,NaN,0,0
5797,5797,<35,No,Undergraduate,1,Man,No,Dev,8,4,India,70368.0,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69865,69865,<35,No,Other,1,Man,No,Dev,0,0,Colombia,6036.0,NaN,0,0
71795,71795,<35,No,Undergraduate,1,Man,No,Dev,7,3,Bangladesh,5460.0,NaN,0,0
72153,72153,>35,Yes,Other,1,Man,No,NotDev,12,2,Germany,106644.0,NaN,0,0
72588,72588,<35,No,Other,1,Man,Yes,Dev,10,6,Spain,41058.0,NaN,0,0
72593,72593,<35,No,Undergraduate,1,Woman,No,Dev,8,5,Ukraine,63600.0,NaN,0,0

for every computer skill==0, HaveWOrkedWith will be missing

In [8]:
df.rename(columns={'Age' : 'AgeAbove35'}, inplace=True)

In [9]:
df['AgeAbove35']=df['AgeAbove35'].replace('>35' , 1).replace('<35' , 0)

In [10]:
df['AgeAbove35']

0        0
1        0
2        0
3        0
4        1
        ..
73457    0
73458    1
73459    0
73460    0
73461    0
Name: AgeAbove35, Length: 73462, dtype: object

In [11]:
df['Country'].value_counts()

Country
United States of America                                14696
Germany                                                  5395
India                                                    5360
United Kingdom of Great Britain and Northern Ireland     4688
Canada                                                   2779
                                                        ...
Gambia                                                      1
Burkina Faso                                                1
Mauritania                                                  1
Burundi                                                     1
Seychelles                                                  1
Name: count, Length: 172, dtype: int64

In [12]:
df['HaveWorkedWith'].value_counts()

HaveWorkedWith
Python                                                                                                                     71
Python;Git                                                                                                                 54
C++;Python                                                                                                                 49
C++                                                                                                                        41
C++;Python;Git                                                                                                             36
                                                                                                                           ..
C;C#;C++;Microsoft Azure;SQLite                                                                                             1
C#;HTML/CSS;JavaScript;TypeScript;Docker;Kubernetes;npm;Angular;ASP.NET Core ;React.js;Cassandra;MariaDB;Redis              1
C#;HTML/CSS;Java;JavaScript;npm;ASP.NET Core ;AWS;DigitalOcean;Managed Hosting;MySQL;PostgreSQL                             1
HTML/CSS;JavaScript;TypeScript;Docker;Express;Node.js;React.js;AWS;Firebase;Heroku;MongoDB;PostgreSQL                       1
C#;HTML/CSS;JavaScript;SQL;TypeScript;npm;Yarn;Angular;ASP.NET;jQuery;React.js;AWS;DynamoDB;Microsoft SQL Server;SQLite     1
Name: count, Length: 69980, dtype: int64

In [13]:
df['HaveWorkedWith']=df['HaveWorkedWith'].str.split(';')
skills=df[['id','HaveWorkedWith']].explode(column='HaveWorkedWith')

In [14]:
skills

          id        HaveWorkedWith
0          0                   C++
0          0                Python
0          0                   Git
0          0            PostgreSQL
1          1            Bash/Shell
...      ...                   ...
73460  73460              DynamoDB
73460  73460  Microsoft SQL Server
73460  73460                SQLite
73461  73461                Python
73461  73461                Docker

[986527 rows x 2 columns]

In [15]:
df['MainBranch'].value_counts()

MainBranch
Dev       67396
NotDev     6066
Name: count, dtype: int64

In [16]:
df['Accessibility'] = df['Accessibility'].str == "Yes"

In [17]:
df['MentalHealth'] = df['MentalHealth'].str == "Yes"

In [21]:
df.to_csv('data/cleaned/employment_cleaned.csv', index=False)

In [22]:
skills.to_csv('data/cleaned/skills.csv', index=False)